name: Call cleanup of images and services created for PR in Gcloud

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the staging branch
  pull_request:
    branches: [ staging ]
    types: [ closed ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Send webhook event to gcloud cloudbuild
        env:
          PR_NUMBER: ${{ github.event.number}}
        run: curl -X POST -H "application/json" "https://cloudbuild.googleapis.com/v1/projects/collaboration-app-staging/triggers/collaboration-app-testing-cleanup:webhook?key=AIzaSyCKxePFEoCsjqtMMOrxm3qGcFLQn-AWJZM&secret=WEBHOOK_TEST_SECRET_VALUE" -d "{ \"PRNUMBER\":$PR_NUMBER }"


